In [37]:
import numpy as np

In [38]:
x = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

In [39]:
# build the model

num_epochs = 60000

# initialize weights

syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [40]:
print(syn0)

[[ 0.8560228   0.33765776  0.09137081  0.80696847]
 [-0.4948208  -0.96400122  0.60303951  0.28048321]
 [-0.62122946 -0.56272042 -0.35731922  0.40795668]]


In [41]:
print(syn1)

[[ 0.71834615]
 [-0.53312238]
 [ 0.94109216]
 [-0.36923394]]


In [42]:
def nonlin(x, deriv=False):
    if (deriv==True):
        return x * (1-x)
    return 1/(1+np.exp(-x))

In [43]:
# Train the model

for j in range(num_epochs):
    # feed forward through layers 0 (input), 1 (hidden), 2 (final/output)
    layer_0 = x
    layer_1 = nonlin(np.dot(layer_0, syn0))
    layer_2 = nonlin(np.dot(layer_1, syn1))
    
    # How much did we miss the target value?
    layer_2_error = y - layer_2
    
    if (j % 10000) == 0:
        print('Error:' + str(np.mean(np.abs(layer_2_error))))
        
    
    # In what direction is the target value?
    layer_2_delta = layer_2_error * nonlin(layer_2, deriv=True)
    
    # How much did each layer_1 value contribute to layer_2_error?
    layer_1_error = layer_2_delta.dot(syn1.T)
    
    layer_1_delta = layer_1_error * nonlin(layer_1, deriv=True)
    
    syn1 += layer_1.T.dot(layer_2_delta)
    syn0 += layer_0.T.dot(layer_1_delta)

Error:0.500298520166


Error:0.00946489957859


Error:0.00652802494188


Error:0.00527197445295


Error:0.00453546433187


Error:0.00403795447917
